spring:
  shardingsphere:
    datasource:
      names: ds-master0,ds-master1,ds-master0-slave0,ds-master1-slave0
      ds-master0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_dsMaster0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: api
        password: 'p'
        maximumPoolSize: 3
      ds-master0-slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_dsMaster0Slave0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: api
        password: 'p'
        maximumPoolSize: 3
      dsMaster1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_dsMaster1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: api
        password: 'p'
        maximumPoolSize: 3
      dsMaster1Slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_dsMaster1Slave0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: api
        password: 'p'
        maximumPoolSize: 3
    sharding:
      binding-tables: t_order,t_order_item  # 绑定表，不会跨库关联
      broadcast-tables: t_dict # 广播表，每个库中数据一样，多为字典表
      master-slave-rules:
        ds-0:
          master-data-source-name: dsMaster0
          slave-data-source-names: dsMaster0Slave0
        ds-1:
          master-data-source-name: dsMaster1
          slave-data-source-names: dsMaster1Slave0
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds-$->{user_id % 2}
      tables:
        t_order:
          actual-data-nodes: ds-$->{0..1}.t_order_$->{0..1}
          key-generator:
            column: order_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          database-strategy:
            hint:
              algorithm-class-name: java.lang.Integer
          table-strategy:
            standard:
              precise-algorithm-class-name: com.ozz.shadingjdbc.component.db.MyStandardShardingAlgorithm
              range-algorithm-class-name: com.ozz.shadingjdbc.component.db.MyStandardShardingAlgorithm
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: ds-$->{0..1}.t_order_item_$->{0..1}
          key-generator:
            column: order_item_id
            props:
              worker:
                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: t_order_item_$->{order_id % 2}
              sharding-column: order_id
