# 配置说明
# https://shardingsphere.apache.org/document/5.5.1/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

props:
  sql-show: true

dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds0?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    maxLifetime: 1500000
  slave0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds1?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    maxLifetime: 1500000
  shardingDs_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds2?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    maxLifetime: 1500000


rules:

- !READWRITE_SPLITTING
  dataSourceGroups:
    shardingDs_0:
      writeDataSourceName: master
      readDataSourceNames:
        - slave0
      # 事务内读请求的路由策略，可选值：PRIMARY（路由至主库）、FIXED（同一事务内路由至固定数据源）、DYNAMIC（同一事务内路由至非固定数据源）。默认值：DYNAMIC
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: round_robin
  loadBalancers:
    round_robin:
      # https://shardingsphere.apache.org/document/current/cn/user-manual/common-config/builtin-algorithm/load-balance/
      type: ROUND_ROBIN

- !SHARDING
  tables:
    t_sharding:
      actualDataNodes: shardingDs_${0..1}.t_sharding_${0..1}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: t_sharding_inline
      databaseStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: database_inline
  defaultDatabaseStrategy:
    standard:
      shardingColumn: id
      shardingAlgorithmName: database_default
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_default:
      type: INLINE
      props:
        algorithm-expression: shardingDs_0
    database_inline:
      type: INLINE
      props:
        algorithm-expression: shardingDs_${id % 2}
    t_sharding_inline:
      type: INLINE
      props:
        algorithm-expression: t_sharding_${id % 2}
