## 配置说明
## https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-spring-boot

spring:
  profiles.active: dev
#  shardingsphere:
#    props:
#      sql.show: true #是否开启SQL显示，默认值: false
#      executor.size: #工作线程数量，默认值: CPU核数
#      max.connections.size.per.query: # 每个查询可以打开的最大连接数量,默认为1
#      check.table.metadata.enabled: #是否在启动时检查分表元数据一致性，默认值: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true
