# 配置说明
# https://shardingsphere.apache.org/document/5.5.1/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

props:
  sql-show: true

dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds_m?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    idleTimeout: 600000
    maxLifetime: 1500000

rules:
- !ENCRYPT
  tables:
    t_master_slave:
      columns:
        name:
          cipher:
            name: name
            encryptorName: my-encryptor

  encryptors:
    my-encryptor:
      type: myEncryptor
      props:
        aes-key-value: my-key
