spring:
  shardingsphere:
    datasource:
      names:
        ds-master,ds-slave0
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://jw_db:3306/api?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
        username: api
        password: p
        maximumPoolSize: 3
      ds-slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://jw_db:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
        username: api
        password: p
        maximumPoolSize: 3
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave0
    props:
      sql:
        show: true
      check:
        table:
          metadata:
            enabled: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ozz.split.model
  type-aliases-super-type: com.ozz.split.model.BaseObject
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true