spring:
  shardingsphere:
    datasource:
      names:
        ds-master,ds-slave0
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: net.sf.log4jdbc.DriverSpy
        jdbcUrl: jdbc:log4jdbc:mysql://jw_db:3306/api?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
        username: api
        password: p
        maximumPoolSize: 3
        maxLifetime: 1800000
      ds-slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://jw_db:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
        username: api
        password: p
        maximumPoolSize: 3
        maxLifetime: 1800000
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave0
    props:
      sql.show: true #是否开启SQL显示，默认值: false
#      executor.size: #工作线程数量，默认值: CPU核数
#      max.connections.size.per.query: # 每个查询可以打开的最大连接数量,默认为1
#      check.table.metadata.enabled: #是否在启动时检查分表元数据一致性，默认值: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ozz.split.model
  type-aliases-super-type: com.ozz.split.model.BaseObject
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true
