# 配置说明
# https://shardingsphere.apache.org/document/5.5.1/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

props:
  sql-show: true

dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds_m?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    maxLifetime: 1500000
  salve0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#     driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:mysql://my_db:5306/demo_ds_s?serverTimezone=Hongkong
    username: myUser
    password: p
    maximumPoolSize: 3
    minIdle: 0
    maxLifetime: 1500000

rules:
- !SINGLE
  tables:
    - "*.*"
- !READWRITE_SPLITTING
  dataSourceGroups:
    readwrite_ds:
      writeDataSourceName: master
      readDataSourceNames:
        - salve0
      # 事务内读请求的路由策略，可选值：PRIMARY（路由至主库）、FIXED（同一事务内路由至固定数据源）、DYNAMIC（同一事务内路由至非固定数据源）。默认值：DYNAMIC
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: round_robin
  loadBalancers:
    round_robin:
      # https://shardingsphere.apache.org/document/current/cn/user-manual/common-config/builtin-algorithm/load-balance/
      type: ROUND_ROBIN

